# Generated by Django 3.0.7 on 2020-09-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_auto_20200906_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(default='0000-0001', max_length=9, null=True),
        ),
    ]
